// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

import "github.com/ovn-kubernetes/libovsdb/model"

const MACBindingScopeTable = "MAC_Binding_Scope"

// MACBindingScope defines an object in MAC_Binding_Scope table
type MACBindingScope struct {
	UUID                      string            `ovsdb:"_uuid"`
	AlwaysLearnFromArpRequest *bool             `ovsdb:"always_learn_from_arp_request"`
	DisableGarpRarp           *bool             `ovsdb:"disable_garp_rarp"`
	ExternalIDs               map[string]string `ovsdb:"external_ids"`
	MACBindingAgeThreshold    *string           `ovsdb:"mac_binding_age_threshold"`
	Name                      string            `ovsdb:"name"`
}

func (a *MACBindingScope) GetUUID() string {
	return a.UUID
}

func (a *MACBindingScope) GetAlwaysLearnFromArpRequest() *bool {
	return a.AlwaysLearnFromArpRequest
}

func copyMACBindingScopeAlwaysLearnFromArpRequest(a *bool) *bool {
	if a == nil {
		return nil
	}
	b := *a
	return &b
}

func equalMACBindingScopeAlwaysLearnFromArpRequest(a, b *bool) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if a == b {
		return true
	}
	return *a == *b
}

func (a *MACBindingScope) GetDisableGarpRarp() *bool {
	return a.DisableGarpRarp
}

func copyMACBindingScopeDisableGarpRarp(a *bool) *bool {
	if a == nil {
		return nil
	}
	b := *a
	return &b
}

func equalMACBindingScopeDisableGarpRarp(a, b *bool) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if a == b {
		return true
	}
	return *a == *b
}

func (a *MACBindingScope) GetExternalIDs() map[string]string {
	return a.ExternalIDs
}

func copyMACBindingScopeExternalIDs(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalMACBindingScopeExternalIDs(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *MACBindingScope) GetMACBindingAgeThreshold() *string {
	return a.MACBindingAgeThreshold
}

func copyMACBindingScopeMACBindingAgeThreshold(a *string) *string {
	if a == nil {
		return nil
	}
	b := *a
	return &b
}

func equalMACBindingScopeMACBindingAgeThreshold(a, b *string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if a == b {
		return true
	}
	return *a == *b
}

func (a *MACBindingScope) GetName() string {
	return a.Name
}

func (a *MACBindingScope) DeepCopyInto(b *MACBindingScope) {
	*b = *a
	b.AlwaysLearnFromArpRequest = copyMACBindingScopeAlwaysLearnFromArpRequest(a.AlwaysLearnFromArpRequest)
	b.DisableGarpRarp = copyMACBindingScopeDisableGarpRarp(a.DisableGarpRarp)
	b.ExternalIDs = copyMACBindingScopeExternalIDs(a.ExternalIDs)
	b.MACBindingAgeThreshold = copyMACBindingScopeMACBindingAgeThreshold(a.MACBindingAgeThreshold)
}

func (a *MACBindingScope) DeepCopy() *MACBindingScope {
	b := new(MACBindingScope)
	a.DeepCopyInto(b)
	return b
}

func (a *MACBindingScope) CloneModelInto(b model.Model) {
	c := b.(*MACBindingScope)
	a.DeepCopyInto(c)
}

func (a *MACBindingScope) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *MACBindingScope) Equals(b *MACBindingScope) bool {
	return a.UUID == b.UUID &&
		equalMACBindingScopeAlwaysLearnFromArpRequest(a.AlwaysLearnFromArpRequest, b.AlwaysLearnFromArpRequest) &&
		equalMACBindingScopeDisableGarpRarp(a.DisableGarpRarp, b.DisableGarpRarp) &&
		equalMACBindingScopeExternalIDs(a.ExternalIDs, b.ExternalIDs) &&
		equalMACBindingScopeMACBindingAgeThreshold(a.MACBindingAgeThreshold, b.MACBindingAgeThreshold) &&
		a.Name == b.Name
}

func (a *MACBindingScope) EqualsModel(b model.Model) bool {
	c := b.(*MACBindingScope)
	return a.Equals(c)
}

var _ model.CloneableModel = &MACBindingScope{}
var _ model.ComparableModel = &MACBindingScope{}
