// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

import "github.com/ovn-kubernetes/libovsdb/model"

const SharedMACBindingTable = "Shared_MAC_Binding"

// SharedMACBinding defines an object in Shared_MAC_Binding table
type SharedMACBinding struct {
	UUID      string `ovsdb:"_uuid"`
	IP        string `ovsdb:"ip"`
	MAC       string `ovsdb:"mac"`
	Scope     string `ovsdb:"scope"`
	Timestamp int    `ovsdb:"timestamp"`
}

func (a *SharedMACBinding) GetUUID() string {
	return a.UUID
}

func (a *SharedMACBinding) GetIP() string {
	return a.IP
}

func (a *SharedMACBinding) GetMAC() string {
	return a.MAC
}

func (a *SharedMACBinding) GetScope() string {
	return a.Scope
}

func (a *SharedMACBinding) GetTimestamp() int {
	return a.Timestamp
}

func (a *SharedMACBinding) DeepCopyInto(b *SharedMACBinding) {
	*b = *a
}

func (a *SharedMACBinding) DeepCopy() *SharedMACBinding {
	b := new(SharedMACBinding)
	a.DeepCopyInto(b)
	return b
}

func (a *SharedMACBinding) CloneModelInto(b model.Model) {
	c := b.(*SharedMACBinding)
	a.DeepCopyInto(c)
}

func (a *SharedMACBinding) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *SharedMACBinding) Equals(b *SharedMACBinding) bool {
	return a.UUID == b.UUID &&
		a.IP == b.IP &&
		a.MAC == b.MAC &&
		a.Scope == b.Scope &&
		a.Timestamp == b.Timestamp
}

func (a *SharedMACBinding) EqualsModel(b model.Model) bool {
	c := b.(*SharedMACBinding)
	return a.Equals(c)
}

var _ model.CloneableModel = &SharedMACBinding{}
var _ model.ComparableModel = &SharedMACBinding{}
